rust:
  directory: ./loro-rs

ios:
  frameworkName: build/LoroFfiFramework
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios

android:
  targets:
    - arm64-v8a
    - armeabi-v7a
    # - x86_64
