// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "loro-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "LoroReactNativeSpec.h"

@interface LoroReactNative : NSObject <NativeLoroReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface LoroReactNative : NSObject <RCTBridgeModule>
#endif

@end